### ISSUE TITLE
Can't scroll child components

### ISSUE THREAD

**Issue by socca1157** [VikLiegostaiev/react-page-scroller#11]
Attempting to use a Select and AsyncSelect list and unable to scroll through the modal without scrolling to next page. Breaks UX of majority of child components. Any advice?

**Comment by monkeydri** [comment]
`ReactPageScroller` use native events instead of React SyntheticEvent : https://github.com/VikLiegostaiev/react-page-scroller/blob/6959f6a4731f57758a1df92c198da1b01e746b34/src/index.js#L53

Therefore setting `event.nativeEvent.stopImmediatePropagation();` on the div you want to scroll should prevent the container used by `ReactPageScroller`  from receiving wheel events (ex shown here : https://gist.github.com/ggregoire/ce7bc946212920c0a6bad8125567d001) but for some reason it does not work. ex `<div onWheel={(e) => { console.log('I am being rolled over'); e.stopPropagation(); e.nativeEvent.stopImmediatePropagation(); }}>`.

I had the same problem than yours so I forked react-page-scroller so it uses React SyntheticEvent instead : https://github.com/monkeydri/react-page-scroller/blob/a2526ab36ef92f6fd961e27acb362a13fcb0de37/src/index.js#L138. I made a PR.

We can then stop the propagation of the wheel event using `e.stopPropagation();`, ex : <div onWheel={(e) => { console.log('I am being rolled over'); e.stopPropagation(); }}>.

works like a charm on my app (which contains multiple nested scrollable elements).

*A good article on native vs React (Synthetic) events is here : https://dlinau.wordpress.com/2015/09/16/avoid-mixing-reacts-event-system-with-native-dom-event-handling/*
