### ISSUE TITLE
How to disable on mobile

### ISSUE THREAD

**Issue by krishnahm** [VikLiegostaiev/react-page-scroller#26]
How to disable on mobile sites?

**Comment by VikLiegostaiev** [comment]
Hi @krishnahm, when screen size is mobile you can just render your components without the pageScroller. You can use: https://github.com/contra/react-responsive. Check "Rendering with a child function" section on their main page. Hope it helps.

**Comment by johhansantana** [comment]
hey @VikLiegostaiev I am having this trouble as well.

For example, if I have the 
```
<ReactPageScroller>
  <Section1/>
  <Section2/>
</ReactPageScroller>
```

Each of the children will be a section to scroll but if I want to conditionally remove the `<ReactPageScroller/>` I would need to wrap my children in a parent of their own, thus, removing the ability of the `<ReactPageScroller/>` to scroll since it will interpret that it only has one section to scroll to.

```javascript
const renderContent = () => {
  if (desktop) {
    return (
      <ReactPageScroller>
        <Section1/>
        <Section2/>
      </ReactPageScroller>
    )
  } else {
    return (
      <div>
        <Section1/>
        <Section2/>
      </div>
    )
  }
}
```

This example I would need to repeat the children in both conditions.

Do you know any other easier way to do this?

**Comment by johhansantana** [comment]
So I was able to do a workaround using the code below:

```javascript
const renderChildren = () => {
    return [
        <Section1 />,
        <Section2 />,
        <Section3 />
    ]
}
```
This returns an array of react nodes which works without having to wrap them with a parent component/element:

```javascript
<MediaQuery maxDeviceWidth={1000}>{renderChildren()}</MediaQuery>
<MediaQuery minDeviceWidth={1001}>
    <ReactPageScroller>
        {renderChildren()}
    </ReactPageScroller>
</MediaQuery>
```
