### ISSUE TITLE
Scroll stops at mobile

### ISSUE THREAD

**Issue by kirilinsky** [VikLiegostaiev/react-page-scroller#35]
hi! awesome package,
but i have an issue:
on mobile device when you tap and switch pages, scrolled only the first page, another disabled. 

 
![5C2ECVr4B4](https://user-images.githubusercontent.com/37263320/69428602-b1c98c80-0d42-11ea-9a6b-a095a3520cc5.gif)

**Comment by jpasuresh** [comment]
Same Issue any fix

**Comment by eyecandycode** [comment]
Elicits the following error in Chrome: [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

...I've tried a few of the suggested remedies - CSS fixes, and adding `{passive: false}` to touch eventListeners, but had no joy so far. Will let you know if that changes.

**Comment by AlexandrDobrovolskiy** [comment]
Same

**Comment by marlonchalegre** [comment]
I fixed the issue adding { passive: false } and putting the preventDefault inside the callback called by the addEventListener and removed the original preventDefault a few lines before the addEventListener. But, in mobile, the setComponentIndex is not setting the state and I can't change the view (the onPageChange works) because of that I didnt create a PR.

**Comment by VikLiegostaiev** [comment]
Hi guys, fixed here: https://github.com/VikLiegostaiev/react-page-scroller/releases/tag/2.0.2-beta
