### ISSUE TITLE
[feature-request] option for callback before page was scrolled

### ISSUE THREAD

**Issue by Puvvl** [VikLiegostaiev/react-page-scroller#40]
Hello @VikLiegostaiev. Can you add into library callback before page was scrolled?
This will help to animate custom elements during page was scrolled.

**Comment by VikLiegostaiev** [comment]
Hi @Puvvl , this shouldn't be part of the library as u can watch the events before page was scrolled by urself. E.g. u can set customPageNumber or listen to mouse or touch events....

**Comment by mohitiihglobal** [comment]
@VikLiegostaiev but that variable we give to ```customPageNumber```, only gets change after the  component got scrolled, we do not have access to onWheel event or onPageChange "type" event.
How we can achieve it here?

**Comment by mohitiihglobal** [comment]
@Puvvl did u get any idea how to get id done manually?

**Comment by Koleja** [comment]
@mohitiihglobal that worked for me: 
customPageNumber={setTimeout(() => {
          return currentPage
        }, 1000)}

**Comment by mohitiihglobal** [comment]
This hook holds my custom Page numbers
`
    const [ pageNo, setPageNo ] = useState(0);
`

This is my pageOnChange callback
`const pageOnChange = (data)=>{
        setPageNo(data)
 }`

I had `customPageNumber` prop set to `pageNo`
so i changed this, to below
`customPageNumber={setTimeout(() => {
        return pageNo
}, 1000)}`

as I understand, I should get `beforePageChange` call in my `pageOnChange` function?

because I am not getting that call, when I start scrolling

**expected behaviour** is to get a call back, when user starts scrolling 

so that I can hide some button, when user start scrolling,
and
show that button when the page has been scrolled.

@Koleja

**Comment by samadiftikhar770** [comment]
I am also stuck with the same situation function onPageChange is called once page is scrolled. I want it to be called before the page scrolled when  the page is start scrolling function i want to call instead of calling it when page is 100% scrolled

**Comment by VikLiegostaiev** [comment]
thanks for feedback, will add this callback

**Comment by samadiftikhar770** [comment]
@VikLiegostaiev  Are you working on this ? or can you guide how i can do this myself. Required Guideline.

**Comment by VikLiegostaiev** [comment]
hey all, added callback `onBeforePageScroll`

**Comment by hugoh59** [comment]
This does not seem to work for me
