### ISSUE TITLE
Using it with nextjs 

### ISSUE THREAD

**Issue by tao101** [VikLiegostaiev/react-page-scroller#73]
Hi I am using this with nextjs and when using the nextjs/link to route to another page I keep getting an error that 

TypeError: Cannot read property 'removeEventListener' of null
or 
TypeError: null is not an object (evaluating 'scrollContainer.current.removeEventListener')

**Comment by andrewfairlie** [comment]
I have also experienced this problem

**Comment by PotLid** [comment]
It seems like whenever routing happens, the pervious component would get dismounted, and the removeEventListener try to remove the bounded event from the certain object existed in the previous page which is not existing in the present moment. So I believe, you can edit the part of the code where it uses removeEventListener. Before you pass the object as an argument to the function, check if that would be still valid or not.

**Comment by adam-dziubinski-mrx** [comment]
It's not a problem with Next or SSR but with [React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#potential-issues), because now the cleanup function from `useEffect` works asynchronously. The solution mentioned in the above article works, so you can extract that package to your bundle and then fix it. I'll try to open PR with a fix.

**Comment by VikLiegostaiev** [comment]
above fix deployed in 2.2.0
